// Every word of «Последняя задача» (lastProblem.js, views/apps/last_problem.ejs,
// js/apps/last-problem.js), in both languages, kept together the way feedbackQuestions.js keeps
// the feedback box: in a game the wording is most of the design, and it is easier to read in one
// place than scattered through templates and locales.
//
// No em or en dashes (the owner's rule for anything the site says), and amounts as "100 ħ".
'use strict';

const COPY = {
    ru: {
        appName: 'Последняя задача',
        appKind: 'мини-приложение',
        host: 'Демон Лапласа',
        question: 'Какая задача будет решена последней?',
        close: 'Закрыть',
        openInChat: 'Открыть в чате',
        tabs: { market: 'Прогноз', top: 'Рейтинг', shop: 'Реакции' },

        welcomeTitle: 'Ваш стартовый баланс',
        welcomeClaim: 'Забрать',
        welcomeNote: 'Вкладывайте кванты в задачи, которые решат позже других, каждое решение другой задачи приносит вам проценты. А за своё решение задачи из списка вы получите премию {bounty} ħ. Кванты игрушечные, а реакции в чате стоят больше стартовой тысячи, так что достаются тем, кто заработал.',
        signIn: 'Войдите, чтобы получить 1 000 ħ и делать прогнозы',
        signInButton: 'Войти',

        balance: 'Баланс',
        groundState: 'Основное состояние · ½ħω',
        opened: 'Открыт 15 сентября вопросом emixter в чате',
        decidedBanner: 'Осталась одна задача, {problem}. Если за 72 часа ничего не изменится, её доли выплатят по полной стоимости.',
        resolvedBanner: 'Последней оказалась {problem}. Доли выплачены, спасибо всем, кто решал и предсказывал.',
        traders: ['участник', 'участника', 'участников'],
        problemsLeft: ['задача осталась', 'задачи осталось', 'задач осталось'],
        listHint: 'В списке все {n} нерешённых задач. Нажмите на задачу, чтобы вложить в неё кванты. Если задачу решат, все остальные вложения получат проценты из последнего столбца.',
        claimedHint: 'Кванты у вас. Выберите задачу в списке и нажмите на неё, чтобы сделать прогноз.',
        columns: { problem: 'Задача и раздел', difficulty: 'Сложность', weight: 'Вес', ifSolved: 'Если решат' },
        payout: 'выплата',
        interest: 'проценты',
        previewGain: 'Если решат {other}, вы получите +{gain} ħ процентов.',
        previewLoss: 'Если решат {problem}, вложенное сгорит.',
        buy: 'Купить',
        sell: 'Продать',
        sellAll: 'Продать всё',
        sellHalf: 'Продать половину',
        bought: 'Куплено',
        sold: 'Продано',
        amount: 'Сумма',
        max: 'Всё',
        confirmBuy: 'Купить за',
        shares: ['долю', 'доли', 'долей'],
        yourPositions: 'Ваши прогнозы',
        worthNow: 'сейчас стоит',
        spent: 'вложено',
        fromChat: 'из чата',
        cancelChatBet: 'Отменить и вернуть',
        solvedList: 'Решены после открытия',
        solvedBy: 'решение',
        statement: 'Условие',
        recent: 'Последние события',
        feedBuy: 'купил(а)',
        feedBuyDemon: 'купил',
        feedSell: 'продал(а)',
        feedSolved: 'решена, выбывает',
        feedRest: 'остальным',
        demonName: 'Демон Лапласа',
        rulesTitle: 'Правила',
        rules: [
            'Рынок открыт 15 сентября, когда emixter спросил в чате, какая задача будет решена последней. В игре задачи, которые тогда были не решены.',
            'Задача считается решённой, когда на сайте появляется её решение на любом языке. Пустой шаблон и заготовка, в которую ничего не написали, не считаются.',
            'Вкладывайте кванты в задачи, которые, по-вашему, решат позже других. Вес задачи это её цена на рынке, веса всех задач вместе дают 100%. Чем больше в задачу вкладывают, тем больше её вес.',
            'Закон сохранения интереса. Когда решают задачу, её доли сгорают, а всё, что вложено в остальные задачи, получает проценты. Чем больше был вес решённой задачи, тем выше ставка. Решат задачу с весом 20%, и остальные получат +25%.',
            'Поэтому чем ближе к концу решат вашу задачу, тем больше процентов она соберёт. Решённая в числе первых принесёт убыток, решённая ближе к концу окупится, даже если она не последняя.',
            'Последняя оставшаяся задача через 72 часа выплачивает полную стоимость своих долей, сверх всех собранных процентов. Эти 72 часа нужны, чтобы отменить выбывание по ошибочно опубликованному решению.',
            'Премия за решение. Кто первым опубликует решение задачи из списка, получит {bounty} ħ. Решать можно и задачу, в которую вложились сами, только её доли тогда сгорят.',
            'Купить и продать можно в любой момент, второй стороной сделки выступает сам рынок (LMSR), поэтому каждая сделка двигает веса. Рынок держит глубину 1000 ħ, так что 100 ħ поднимают задачу с весом 3% примерно до 12%.',
            'Кванты игрушечные, их нельзя купить за деньги или вывести. На них покупаются реакции, и каждая стоит больше стартовой тысячи, поэтому купить её можно только на заработанное.',
        ],

        topTitle: 'Лучшие прогнозы',
        topEmpty: 'Пока никто не сделал прогноз. Будьте первым.',
        profit: 'прибыль',
        you: 'вы',
        benchmark: 'эталон',

        shopTitle: 'Реакции за кванты',
        shopNote: 'Каждая реакция стоит больше стартовой тысячи, её можно купить только на заработанное. Купленная остаётся у вас навсегда, в чате и под решениями.',
        owned: 'Ваша',
        buyFor: 'Купить за',
        offSeason: 'Продаётся с 23 сентября по 23 октября',
        trophy: 'Трофей, не продаётся',
        never: 'Не продаётся',
        trophyHow: {
            ':n2000:': 'Достанется автору 2000-го решения на сайте',
            ':last:': 'Достанется тому, кто решит последнюю задачу',
        },
        perpetuumRefusal: 'Патентное бюро отклонило заявку, она нарушает первое начало термодинамики.',
        unlocked: 'Реакция ваша',
        confirm: 'Точно?',

        notesTitle: 'Заметки демона',
        notes: [
            'Я пересчитал модель 18 сентября. За две недели на сайте решили 35 задач, 14 из них за первые три дня рынка. На каждую нерешённую задачу это примерно в 15 раз чаще, чем в среднем за год, и мой прошлый прогноз в 261 день можно выбросить.',
            'Модель та же, 37 недель истории и 532 первых решения. На неделях после 20 июля, которых она не видела при обучении, AUC 0,73.',
            'Лучше всего предсказывает, когда задачу решат, оценка времени на решение, каждое стандартное отклонение почти вдвое снижает шанс за неделю. Длинные условия тоже решают позже, Valter был прав.',
            'Почти решённый раздел затягивает свои хвосты сильнее всего остального, а задачи в конце раздела решают позже. Звёздочка ∗ последней задачу не делает, их решают даже чуть охотнее.',
            'В ближайшие 7 дней скорее всего решат 8.2.2, 14.4.19 и 8.2.33, а последними, скорее всего, останутся 6.6.27, 7.2.13 и 7.2.12. Шанс каждой задачи я показываю под ней, когда её открываешь.',
            'По 6 000 прогонам при нынешнем темпе за неделю решат около 8 задач. Когда темп вернётся к обычному, последние задачи будут держаться месяцами.',
            'Рынок переоценил 7.2.14 и 14.3.8, поэтому я продал свои доли в них и вложил кванты в задачи, которые считаю недооценёнными.',
        ],

        amountEggs: {
            137: 'α⁻¹ ≈ 137. Постоянная тонкой структуры одобряет',
            273: '273 K это 0 °C. Холоднокровная ставка',
            666: 'Число демона. Лапласа, разумеется',
            1836: 'mₚ/mₑ ≈ 1836. Протон доволен',
            2023: 'Ровно столько задач в задачнике, и в этом году родился сайт',
        },
        // 5.8.9 was declared the most horrifying problem in the book on 15 Sep, so that nobody would
        // solve it and spoil a bet; its "followers", it was explained, do not like to lose.
        problemEggs: {
            '5.8.9': 'Осторожно, у этой задачи есть последователи, и они не любят проигрывать. Не злите их.',
        },
        collapse: 'Коллапс волновой функции',
        birthday: 'Savchenko Solutions 3 года',

        errors: {
            auth: 'Сначала войдите',
            amount: 'Введите целое число квантов',
            insufficient: 'Не хватает квантов',
            closed: 'Эта задача уже не в игре',
            not_held: 'У вас нет этих долей',
            shares: 'Не то число долей',
            side: 'Что-то пошло не так',
            owned: 'Эта реакция уже ваша',
            off_season: 'Сейчас не продаётся',
            never: 'Не продаётся',
            trophy: 'Трофей не продаётся',
            rate_limited: 'Слишком часто, подождите минуту',
            cross_site: 'Запрос пришёл не с сайта',
            not_open: 'Рынок закрыт',
            server: 'Не получилось, попробуйте ещё раз',
        },

        card: {
            open: 'Открыть',
            leaders: 'Лучшие прогнозы',
            nobody: 'Прогнозов пока нет',
            progress: 'Решено {solved} из {total}',
            bounty: 'Решите задачу из списка и получите {amount} ħ',
        },
        soonLine: 'По расчёту демона, её решат в ближайшие 7 дней с шансом {p}.',
        shortBy: 'не хватает {n} ħ',

        notify: {
            chatBetTitle: 'Ваша ставка из чата учтена',
            chatBet: (problem, amount) => `${problem}, ${amount} ħ в «Последней задаче», как вы написали в чате. Если передумаете, отмените ставку в приложении, и кванты вернутся полностью.`,
            solvedTitle: (problem) => `${problem} решена и выбывает`,
            solvedLost: (problem, who) => `${who ? `Решение опубликовал(а) ${who}. ` : ''}Ваши доли этой задачи сгорели, а проценты, которые они собрали раньше, остаются у вас.`,
            interestTitle: (amount) => `Проценты +${amount} ħ`,
            interest: (problem, rate, lost) => `Решена ${problem}, и всё, что у вас вложено в задачи в игре, принесло ${rate}.${lost ? ` Доли ${problem} сгорели.` : ''} Кванты на балансе.`,
            decidedTitle: (problem) => `Осталась одна задача, ${problem}`,
            decided: 'Если за 72 часа ничего не изменится, её доли выплатят по полной стоимости.',
            payoutTitle: (amount) => `Выплата +${amount} ħ`,
            payout: (problem) => `${problem} оказалась последней задачей. Кванты на балансе.`,
            trophyTitle: (name) => `Трофей «${name}»`,
            bountyTitle: (amount, count) => `Премия +${amount} ħ за ${count > 1 ? 'решения' : 'решение'}`,
            bounty: (problems, each, count) => `Спасибо за ${count > 1 ? 'решения' : 'решение'} ${problems}. Каждое решение задачи из «Последней задачи» приносит автору ${each} ħ, кванты уже на балансе.`,
            trophyN2000: 'Вы опубликовали 2000-е решение на сайте. Эта реакция теперь только ваша.',
            trophyLast: 'Вы решили последнюю задачу Савченко на сайте. Эта реакция теперь только ваша.',
            announceTitle: 'Последняя задача, прогнозы открыты',
            announce: 'Какая задача будет решена последней? У каждого 1 000 ħ на прогнозы.',
        },
    },

    en: {
        appName: 'The Last Problem',
        appKind: 'mini app',
        host: "Laplace's demon",
        question: 'Which problem will be solved last?',
        close: 'Close',
        openInChat: 'Open in chat',
        tabs: { market: 'Predict', top: 'Leaders', shop: 'Reactions' },

        welcomeTitle: 'Your starting balance',
        welcomeClaim: 'Claim',
        welcomeNote: 'Put quanta on the problems that will be solved later than the rest, and every other problem solved pays you interest. Solve a problem on the list yourself and you get a {bounty} ħ bounty. Quanta are play money, and chat reactions cost more than the starting thousand, so they go to those who earn them.',
        signIn: 'Sign in to get 1,000 ħ and make predictions',
        signInButton: 'Sign in',

        balance: 'Balance',
        groundState: 'Ground state · ½ħω',
        opened: 'Opened on 15 September by emixter\'s question in the chat',
        decidedBanner: 'One problem left, {problem}. If nothing changes within 72 hours, its shares pay their full value.',
        resolvedBanner: 'The last one was {problem}. Shares are paid; thank you to everyone who solved and predicted.',
        traders: ['trader', 'traders'],
        problemsLeft: ['problem left', 'problems left'],
        listHint: 'All {n} unsolved problems are listed. Tap a problem to put quanta on it. If a problem is solved, everything on the others earns the interest in the last column.',
        claimedHint: 'The quanta are yours. Pick a problem in the list and tap it to make a prediction.',
        columns: { problem: 'Problem and section', difficulty: 'Difficulty', weight: 'Weight', ifSolved: 'If solved' },
        payout: 'payout',
        interest: 'interest',
        previewGain: 'If {other} is solved, you get +{gain} ħ in interest.',
        previewLoss: 'If {problem} is solved, the stake is lost.',
        buy: 'Buy',
        sell: 'Sell',
        sellAll: 'Sell all',
        sellHalf: 'Sell half',
        bought: 'Bought',
        sold: 'Sold',
        amount: 'Amount',
        max: 'Max',
        confirmBuy: 'Buy for',
        shares: ['share', 'shares'],
        yourPositions: 'Your predictions',
        worthNow: 'worth now',
        spent: 'spent',
        fromChat: 'from chat',
        cancelChatBet: 'Cancel and refund',
        solvedList: 'Solved since the market opened',
        solvedBy: 'solution by',
        statement: 'Statement',
        recent: 'Latest',
        feedBuy: 'bought',
        feedBuyDemon: 'bought',
        feedSell: 'sold',
        feedSolved: 'solved, out of the market',
        feedRest: 'the rest',
        demonName: "Laplace's demon",
        rulesTitle: 'Rules',
        rules: [
            'The market opened on 15 September, when emixter asked in the chat which problem will be solved last. It covers the problems unsolved at that moment.',
            'A problem counts as solved when its solution appears on the site in either language. An empty template, or one with nothing written into it, does not count.',
            'Put quanta on the problems you think will be solved later than the rest. A problem\'s weight is its price in the market, and the weights of all problems add up to 100%. The more goes into a problem, the heavier it gets.',
            'Conservation of interest. When a problem is solved its shares burn, and everything on the other problems earns interest. The heavier the solved problem was, the higher the rate. If a problem weighing 20% is solved, the rest get +25%.',
            'So the closer to the end your problem is solved, the more interest it collects. One solved among the first loses money, and one solved near the end pays off even if it is not the very last.',
            'The last problem standing pays the full value of its shares after 72 hours, on top of all the interest it collected. The wait is for undoing an elimination caused by a mistaken post.',
            'Bounty for solving. Whoever first posts a solution of a problem on the list gets {bounty} ħ. You may solve a problem you hold, too, only its shares then burn.',
            'You can buy and sell at any moment, and the market itself takes the other side of every trade (LMSR), so every trade moves the weights. The market keeps a depth of 1000 ħ, so 100 ħ lifts a problem weighing 3% to about 12%.',
            'Quanta are play money, so they cannot be bought for money or cashed out. They buy reactions, and each costs more than the starting thousand, so only what you earn can buy one.',
        ],

        topTitle: 'Best predictions',
        topEmpty: 'No predictions yet. Be the first.',
        profit: 'profit',
        you: 'you',
        benchmark: 'benchmark',

        shopTitle: 'Reactions for quanta',
        shopNote: 'Every reaction costs more than the starting thousand, so only what you earn buys one. Once bought it is yours for good, in the chat and under solutions.',
        owned: 'Yours',
        buyFor: 'Buy for',
        offSeason: 'On sale from 23 September to 23 October',
        trophy: 'Trophy, not for sale',
        never: 'Not for sale',
        trophyHow: {
            ':n2000:': 'Goes to the author of the 2000th solution on the site',
            ':last:': 'Goes to whoever solves the last problem',
        },
        perpetuumRefusal: 'The patent office rejected the application, since it violates the first law of thermodynamics.',
        unlocked: 'The reaction is yours',
        confirm: 'Sure?',

        notesTitle: "The demon's notes",
        notes: [
            'I refit my model on 18 September. In two weeks the site solved 35 problems, 14 of them in the first three days of the market. Per unsolved problem that is about 15 times the year\'s average, and my old forecast of 261 days can go in the bin.',
            'The model is the same, 37 weeks of history and 532 first solutions. On the weeks after 20 July, which it did not see while learning, the AUC is 0.73.',
            'The best single predictor of when a problem gets solved is the estimated solving time, and each standard deviation of it nearly halves the weekly chance. Long statements get solved later too, as Valter said.',
            'A nearly finished section pulls in its stragglers more than anything else, and problems late in a section get solved later. The asterisk ∗ does not make a problem last, starred ones are even picked slightly more often.',
            'Within the next 7 days 8.2.2, 14.4.19 and 8.2.33 are the likeliest to go, and 6.6.27, 7.2.13 and 7.2.12 the likeliest to be left last. I show each problem\'s chance under it when you open it.',
            'Across 6,000 simulations about 8 problems get solved within a week at the current pace. When the pace returns to normal, the last few will hold out for months.',
            'The market priced 7.2.14 and 14.3.8 far above my view, so I sold my shares in them and put the quanta into the problems I think are underpriced.',
        ],

        amountEggs: {
            137: 'α⁻¹ ≈ 137. The fine-structure constant approves',
            273: '273 K is 0 °C. A cold-blooded bet',
            666: "The demon's number. Laplace's, of course",
            1836: 'mₚ/mₑ ≈ 1836. The proton is pleased',
            2023: 'Exactly the number of problems in the book, and the year the site was born',
        },
        problemEggs: {
            '5.8.9': 'Careful, this problem has followers, and they do not like to lose. Do not anger them.',
        },
        collapse: 'Wave function collapse',
        birthday: 'Savchenko Solutions turns 3',

        errors: {
            auth: 'Sign in first',
            amount: 'Enter a whole number of quanta',
            insufficient: 'Not enough quanta',
            closed: 'This problem is out of the market',
            not_held: 'You do not hold these shares',
            shares: 'That is not a valid number of shares',
            side: 'Something went wrong',
            owned: 'This reaction is already yours',
            off_season: 'Not on sale right now',
            never: 'Not for sale',
            trophy: 'Trophies are not for sale',
            rate_limited: 'Too fast, wait a minute',
            cross_site: 'That request did not come from the site',
            not_open: 'The market is closed',
            server: 'That did not work, try again',
        },

        card: {
            open: 'Open',
            leaders: 'Best predictions',
            nobody: 'No predictions yet',
            progress: '{solved} of {total} solved',
            bounty: 'Solve a problem on the list and get {amount} ħ',
        },
        soonLine: 'The demon puts the chance it is solved within 7 days at {p}.',
        shortBy: '{n} ħ short',

        notify: {
            chatBetTitle: 'Your bet from the chat is in',
            chatBet: (problem, amount) => `${problem}, ${amount} ħ in The Last Problem, as you wrote in the chat. If you change your mind, cancel it in the app and get every quantum back.`,
            solvedTitle: (problem) => `${problem} is solved and out`,
            solvedLost: (problem, who) => `${who ? `Solution posted by ${who}. ` : ''}Your shares in this problem burned, and the interest they collected before stays yours.`,
            interestTitle: (amount) => `Interest +${amount} ħ`,
            interest: (problem, rate, lost) => `${problem} is solved, and everything you hold in the problems still in play earned ${rate}.${lost ? ` Your shares in ${problem} burned.` : ''} The quanta are in your balance.`,
            decidedTitle: (problem) => `One problem left, ${problem}`,
            decided: 'If nothing changes within 72 hours, its shares pay their full value.',
            payoutTitle: (amount) => `Payout +${amount} ħ`,
            payout: (problem) => `${problem} was the last problem solved. The quanta are in your balance.`,
            trophyTitle: (name) => `Trophy "${name}"`,
            bountyTitle: (amount) => `Bounty +${amount} ħ for solving`,
            bounty: (problems, each, count) => `Thank you for solving ${problems}. Every solution of a problem in The Last Problem earns its author ${each} ħ, and the quanta are in your balance.`,
            trophyN2000: 'You posted the 2000th solution on the site. This reaction is now yours alone.',
            trophyLast: 'You solved the last Savchenko problem on the site. This reaction is now yours alone.',
            announceTitle: 'The Last Problem, predictions are open',
            announce: 'Which problem will be solved last? Everyone has 1,000 ħ to predict with.',
        },
    },
};

function getCopy(lang) {
    return lang === 'ru' ? COPY.ru : COPY.en;
}

/* The part the browser needs, as plain JSON (no functions). */
function clientCopy(lang) {
    const c = getCopy(lang);
    const out = {};
    for (const [key, value] of Object.entries(c)) {
        if (key === 'notify') continue;
        out[key] = value;
    }
    return out;
}

module.exports = { COPY, getCopy, clientCopy };
