// css/bundle.css — the one site stylesheet every page loads (through views/default/site_styles.ejs).
//
// Order matters and is the cascade: the generated @font-face rules, then the data-palette custom
// properties generated from js/palettes.js, then css/design-system.css (tokens, the Bootstrap
// bridge, base elements, components), then css/main_page.css (the homepage). Editing any of the
// sources without re-running `npm run build:css` ships invisible CSS; tests/site-styles.test.js
// compares the committed bundle with buildBundle() to catch exactly that.
const fs = require('fs');
const path = require('path');

const CSS_DIR = path.join(__dirname, '..', 'css');
const SOURCES = ['design-system.css', 'main_page.css'];

function paletteBlock() {
    delete require.cache[require.resolve('../js/palettes')];
    const vars = require('../js/palettes').cssVariables();
    const body = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n');
    return `/* Data palettes — generated from js/palettes.js by scripts/build-css.js. */\n:root {\n${body}\n}`;
}

function fontsBlock() {
    const file = path.join(CSS_DIR, 'vendor', 'fonts', 'site-fonts.css');
    if (!fs.existsSync(file)) return '';
    // site-fonts.css uses url(h/…) relative to css/vendor/fonts/; the bundle lives in css/.
    return fs.readFileSync(file, 'utf8').replace(/url\(h\//g, 'url(vendor/fonts/h/');
}

/** The exact text css/bundle.css must contain. Pure apart from reading the sources. */
function buildBundle() {
    const parts = [
        `/* === site-fonts.css (generated by scripts/build-fonts.py) === */\n${fontsBlock()}`,
        `/* === palettes (generated from js/palettes.js) === */\n${paletteBlock()}`,
        ...SOURCES.map((f) => `/* === ${f} === */\n` + fs.readFileSync(path.join(CSS_DIR, f), 'utf8')),
    ];
    return parts.join('\n\n');
}

if (require.main === module) {
    fs.writeFileSync(path.join(CSS_DIR, 'bundle.css'), buildBundle());
    console.log('CSS bundle created: css/bundle.css');
}

module.exports = { buildBundle, SOURCES };
