-- 038_drop_unused_tables_rollback.sql
-- Recreate the three tables dropped by 038_drop_unused_tables.sql.
-- DDL captured verbatim from production via pg_dump --schema-only before the
-- drop. The tables held no rows, so there is no data to restore.

BEGIN;

CREATE TABLE IF NOT EXISTS public.alternative_solutions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    problem_name character varying(50) NOT NULL,
    language character varying(5) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    method_type character varying(50),
    difficulty_level integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    likes_count integer DEFAULT 0,
    dislikes_count integer DEFAULT 0,
    is_verified boolean DEFAULT false
);

CREATE TRIGGER update_alternative_solutions_updated_at
    BEFORE UPDATE ON public.alternative_solutions
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.user_achievements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    achievement_type character varying(50) NOT NULL,
    achievement_data jsonb,
    earned_at timestamp without time zone DEFAULT now(),
    UNIQUE (user_id, achievement_type)
);

CREATE TABLE IF NOT EXISTS public.sections (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number character varying(10) NOT NULL,
    russian_title text NOT NULL,
    english_title text NOT NULL,
    entries_count integer NOT NULL
);

COMMIT;
